### ISSUE TITLE
Cannot read from i2web repo

### ISSUE THREAD

**Issue by themostharagan** [arcus-smart-home/arcusweb#1]
Hello! It's awesome that you have continued with this project.

I am trying to get an instance of **arcusweb** running with the instructions you wrote in the readme file, but haven't been able to do it yet.
Even though I configured the ssh keys of my bitbucket account correctly, _npm_ is not able to clone the repository **i2web-devtools**. Is that repository private by any chance?
Just letting you know of this problem, maybe you missed opening _i2web_ to the public when uploading the whole Arcus project. If this is not the case, is it still possible for anybody to install arcusweb? how?

Thanks in advance.

**Comment by alancnet** [comment]
Same. I even get access denied at https://bitbucket.org/eyeris/i2web-devtools

**Comment by AndrewX192** [comment]
The devtools were not part of the open source release, but it shouldn't be a problem for getting arcusweb operating.

**Comment by AndrewX192** [comment]
Closing this - this has been resolved for a while, you shouldn't run into this problem when setting up arcusweb.
